version: 2.1

orbs:
  codacy: codacy/base@2.6.4

workflows:
  version: 2
  build:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: populate_cache
          persist_to_workspace: true
          cmd: sbt "set scalafmtUseIvy in ThisBuild := false;+update"
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: check_format
          cmd: sbt scalafmt::test test:scalafmt::test sbt:scalafmt::test
          requires:
            - populate_cache
      - codacy/sbt:
          name: compile
          persist_to_workspace: true
          cmd: sbt "+compile;+test:compile"
          requires:
            - populate_cache
      - codacy/sbt:
          name: test
          cmd: |
            sbt "coverage;test;coverageReport"
            bash <(curl -Ls https://coverage.codacy.com/get.sh)
          requires:
            - compile
            - check_format
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - codacy/sbt:
          name: publish
          context: CodacyAWS
          cmd: |
            sbt "retrieveGPGKeys;+publishSigned;sonatypeBundleRelease"
          requires:
            - tag_version
