version: 2.1

orbs:
  codacy: codacy/base@10.1.0

workflows:
  version: 2
  build:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt_docker:
          name: test
          persist_to_workspace: true
          steps:
            - run:
                name: Enable Coverage
                command: sbt coverage
            - run:
                name: Check scalafmt on scala files
                command: sbt scalafmtCheckAll
            - run:
                name: Check scalafmt on sbt files
                command: sbt scalafmtSbtCheck
            - run:
                name: Check scalafmt on sbt files
                command: sbt scalafmtSbtCheck
            - run:
                name: Run tests
                command: sbt test
            - run:
                name: Generate coverage report
                command: sbt coverageReport
            - run:
                name: Send Coverage results to Codacy
                command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --skip
          requires:
            - codacy/checkout_and_version
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - codacy/sbt_docker:
          name: publish
          context: CodacyAWS
          steps:
            - run:
                name: Retrieve GPG Keys
                command: sbt retrieveGPGKeys
            - run:
                name: Create publish bundle
                command: sbt publishSigned
            - run:
                name: Release bundle to Sonatype
                command: sbt sonatypeBundleRelease
          requires:
            - tag_version
