version: 2.1

orbs:
  codacy: codacy/base@2.14.8

workflows:
  version: 2
  build:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: populate_cache_compile
          persist_to_workspace: true
          cmd: sbt coverage test:compile
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: check_format
          cmd: sbt scalafmt::test test:scalafmt::test sbt:scalafmt::test
          requires:
            - populate_cache_compile
      - codacy/sbt:
          name: test
          cmd: |
            sbt coverage test coverageReport
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report --skip
          requires:
            - populate_cache_compile
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - check_format
            - test
          filters:
            branches:
              only:
                - master
      - codacy/sbt:
          name: publish
          context: CodacyAWS
          cmd: sbt retrieveGPGKeys publishSigned sonatypeBundleRelease
          requires:
            - tag_version
