version: 2.1

orbs:
  codacy: codacy/base@11.2.0

references:
  cache_prefix: &cache_prefix sbt-cache-20240918

workflows:
  version: 2
  build:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: test
          context: ExternalSystems
          cache_prefix: *cache_prefix
          save_cache: true
          aws_profile: maven
          use_sbt_native_client: true
          persist_to_workspace: true
          steps:
            - run:
                name: Enable Coverage
                command: sbt coverage
            - run:
                name: Check scalafmt on scala files
                command: sbt scalafmtCheckAll
            - run:
                name: Check scalafmt on sbt files
                command: sbt scalafmtSbtCheck
            - run:
                name: Run tests
                command: sbt crossTest
            - run:
                name: Generate coverage report
                command: sbt coverageReport
            - run:
                name: Send Coverage results to Codacy
                command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --skip
          requires:
            - codacy/checkout_and_version
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - codacy/sbt:
          name: publish_sonatype
          context: CodacyAWS
          use_sbt_native_client: false
          steps:
            - run:
                name: Add sonatype setting
                command: echo 'publicMvnPublish' > publishing.sbt
            - run:
                name: Retrieve GPG Keys
                command: sbt retrieveGPGKeys
            - run:
                name: Create publish bundle
                command: sbt crossPublishSigned
            - run:
                name: Release bundle to Sonatype
                command: sbt sonatypeBundleRelease
          requires:
            - tag_version
      - codacy/sbt:
          name: publish_s3
          aws_profile: maven
          context: CodacyAWS
          use_sbt_native_client: false
          steps:
            - run:
                name: Add s3 publishing setting
                command: echo 'privateMvnPublish' > publishing.sbt
            - run:
                name: Publish to S3
                command: sbt crossPublish
          requires:
            - tag_version
